auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory # for development, if production env, use etcd/consul
      replication_factor: 1
  chunk_idle_period: 1h
  chunk_target_size: 1048576 # 1MB
  wal:
    enabled: true
    dir: /loki/wal

schema_config:
  configs:
    - from: 2025-11-27
      store: boltdb-shipper # local dev / simple
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    # shared_store đã bỏ
  filesystem:
    directory: /loki/chunks

limits_config:
  ingestion_rate_mb: 20
  ingestion_burst_size_mb: 30
  allow_structured_metadata: false # quan trọng, tránh lỗi validation
  reject_old_samples: false

analytics:
  reporting_enabled: false

compactor:
  working_directory: /loki/compactor
