global:
  scrape_interval: 1m
  evaluation_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "nats"
    static_configs:
      - targets: ["nats:8222"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
  - job_name: "ecommerce-api-gateway"
    static_configs:
      - targets: ["host.docker.internal:8080"]
