name: Tests
on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]
env:
  GO_VERSION: "1.25"
jobs:
  go-lint:
    name: Golang-Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{env.GO_VERSION}}
          cache: true
      - name: Download dependencies
        run: |
          go mod download
          go mod verify
      - name: Install Mockery
        run: go install github.com/vektra/mockery/v2@latest
      - name: Generate mock
        run: mockery
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          install-mode: goinstall # Build golangci-lint with Go 1.25
          args: ./... # read golang lint config from .golangci.yaml
          skip-cache: true
          skip-save-cache: true
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Download dependencies
        run: go mod download
      - name: Install Mockery
        run: go install github.com/vektra/mockery/v2@latest
      - name: Generate mock
        run: mockery
      - name: Run unit test
        run: go test -v $(find . -name "*_test.go" -not -path "./vendor/*" -not -path "./node_modules/*" | xargs -I {} dirname {} | sort -u | sed 's|^\.|.|')
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    needs: [go-lint, unit-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Build all service
        run: |
          go build -o bin/api_gateway ./cmd/main.go
          go build -o bin/auth ./apps/auth/cmd/main.go
          go build -o bin/order ./apps/order/cmd/main.go
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: /bin
